ignored = ["github.com/ethereum/go-ethereum/whisper/notifications"]

[prune]
  unused-packages = true
  go-tests = true

  [[prune.project]]
    name = "github.com/karalabe/hid"
    unused-packages = false

  [[prune.project]]
    name = "github.com/ethereum/go-ethereum"
    unused-packages = false

[[override]]
  name = "github.com/ethereum/go-ethereum"
  branch = "release/1.8"

[[constraint]]
  name = "github.com/mkideal/cli"
  branch = "master"
